dist: trusty
language: python

python:
  - "3.5"

install:
  - pip install networkx coverage nosexcover
  #- pip install nose
  #- pip install mock

script:
  -  nosetests -sv --with-xunit --xunit-file=nosetests.xml --with-xcoverage --xcoverage-file=coverage.xml
  #- ./sh/test.sh
  - sonar-scanner
  #- python main.py
 
addons:
  sonarcloud:
    organization: timbo-rafa-github
